// static content data


module.exports = {
    urls : ["https://seo-elp.fr/#/","https://www.lisi-automotive.com/fr/","http://usainbolt.com/","http://www.iut-bm.univ-fcomte.fr/pages/fr/a-votre-service-13757.html","https://www.angrybirds.com/"],
    lisi_pages : [
        "https://www.lisi-automotive.com/en/products/clipped-solutions/", // eco index : D / green it : D 
        "https://www.lisi-automotive.com/en/multi-material-assembly-solutions/", // E / F 
        "https://www.lisi-automotive.com/en/anti-creep-assembly-solutions/", // E / F 
        "https://www.lisi-automotive.com/en/lisi-insulating-bolt-for-mhev/", // E / E 
        "https://www.lisi-automotive.com/en/products/clipped-solutions/fasteners-for-panels/", // F / G
        "https://www.lisi-automotive.com/en/products/threaded-fasteners/screws-bolts/", // F / F 
        "https://www.lisi-automotive.com/en/products/threaded-fasteners/nuts/", // F / F 
        "https://www.lisi-automotive.com/en/innovation-sealing-screws/" // F / E
    ],
    concurrents : [
        "https://www.ejot.fr/Fixations-Industrielles/Produits/EJOWELD%C2%AE/p/VBT_EJOWELD",
        "https://www.ejot.fr/Fixations-Industrielles/Produits/FDS%C2%AE/p/VBT_FDS",
        "https://www.boellhoff.com/fr-fr/produits-et-services/elements-d-assemblage-speciaux/rivet-auto-poinconneur-rivset.php",
        "https://www.araymond-automotive.com/fr/solutions-de-fixation-et-assemblage/garnitures-de-carrosserie-automobile",
        "https://www.agrati.com/fr/products/licenced-screw/",
        "https://www.nedschroef.com/en/automotive",
        "https://fr.sfs.com/produits/applications-industrielles/fixations-pour-applications-sp%c3%a9ciales/sci-65895?returnurl=%2fproduits%2fapplications-industrielles%2ffixations-pour-applications-sp%25c3%25a9ciales%2f",
        "https://www.stanleyengineeredfastening.com/en/Fasteners/self-piercing-rivets/Tucker-SPR",
        "http://faurecia.com/technologies/mobilite-durable/technologies-reduction-emissions",
        "https://www.valeo.com/fr/electrification-abordable-48-volts/",
        "https://www.plasticomnium.com/fr/design-et-interactivite/",
        "https://www.bosch.com/products-and-services/market-specific-solutions/solutions-for-the-automotive-industry/",
        "https://www.zf.com/products/en/cars/stories/electric_drives_by_zf.html",
        "https://www.ejot.com/Industrial-Fasteners-Division/Products/FDS%C2%AE/p/VBT_FDS",
        "https://www.boellhoff.com/us-en/products-and-services/special-fasteners/high-speed-joining-rivtac.php",
        "https://us.sfs.com/standing-seam-panel-fastening/clip-screws",
        "https://www.agrati.com/special-solutions/electrification/",
        "https://www.rotorclip.com/prod_radial_tapered_section_retaining_rings.php",
        "https://www.nedschroef.com/en/automotive/product-solutions",
        "https://www.araymond-automotive.com/en/joining-technologies/clipping-systems",
        "http://www.brugola.com/en/products/con-rod-bolts",
        "https://www.bulten.com/en/Services/Sustainable-solutions/BUFOe",
        "https://www.kamax.com/loesungen/produktportfolio/",
        "https://www.plasticomnium.com/fr/mobilite-durable/",
        "https://www.lisi-aerospace.com/en/product/hi-lok-and-hi-lite-fasteners/",
        "https://www.lisi-medical.com/page-produits/implants-instruments-orthopedie-1",
        "https://www.piolax.co.jp/en/products/car/"
    ],
    exampleScrapperData :{"size": 5468,
    "nbRequest": 211,
    "domSize": 589,
    "filesNotMin": [],
    "policesUtilise": [
      'https://use.typekit.net/af/e2ec25/00000000000000000000d668/27/l?subset_id=2&fvd=n4&v=3',
      'https://use.typekit.net/af/0708e7/000000000000000000012cf3/27/l?subset_id=2&fvd=n9&v=3',
      'https://use.typekit.net/af/6a91a4/000000000000000000012cef/27/l?subset_id=2&fvd=n5&v=3',
      'https://use.typekit.net/af/43af09/00000000000000000000d667/27/l?subset_id=2&fvd=i4&v=3',
      'https://use.typekit.net/af/f1737c/00000000000000000000d66c/27/l?subset_id=2&fvd=i7&v=3',
      'https://use.typekit.net/af/fe26a1/00000000000000000000d66b/27/l?subset_id=2&fvd=n7&v=3',
      'https://use.typekit.net/af/7807c8/000000000000000000012cf4/27/l?subset_id=2&fvd=i9&v=3',
      'https://use.typekit.net/af/9ed401/000000000000000000012cf0/27/l?subset_id=2&fvd=i5&v=3',
      'https://www.lisi-automotive.com/wp-content/themes/lisi/fonts/AbadiMTPro-ExtraLight.woff',
      'https://www.lisi-automotive.com/wp-content/themes/lisi/fonts/AbadiMTPro-Light.woff',
      'https://fonts.gstatic.com/s/barlow/v12/7cHpv4kjgoGqM7E_DMs5.woff2',
      'https://www.lisi-automotive.com/wp-content/themes/lisi/fonts/AbadiMTPro.woff',
      'https://www.lisi-automotive.com/wp-content/themes/lisi/fonts/glyphicons-halflings-regular.woff2',
      'https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxK.woff2',
      'https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxK.woff2',
      'https://fonts.gstatic.com/s/roboto/v18/KFOlCnqEu92Fr1MmEU9fBBc4.woff2'
    ],
    "etagsNb": 102,
    "imagesWithoutLazyLoading": [
      'https://www.lisi-automotive.com/wp-content/themes/lisi/imgs/picto-aucun-favori.png',
      'https://www.lisi-automotive.com/wp-content/themes/lisi/imgs/picto-aucun-favori.png',
      'https://www.lisi-automotive.com/wp-content/uploads/2019/08/cropped-logo_automotive_rvb.webp',
      'https://www.lisi-automotive.com/wp-content/polylang/en_GB.png',
      'https://www.lisi-automotive.com/wp-content/polylang/fr_FR.png',
      'https://www.lisi-automotive.com/wp-content/polylang/de_DE.png',
      'https://www.lisi-automotive.com/wp-content/uploads/2016/09/Banni%C3%A8re-fine-4-actualites.jpeg',
      'https://www.lisi-automotive.com/wp-content/themes/lisi/imgs/picto-loupe-news.png',
      'https://www.lisi-automotive.com/wp-content/uploads/2022/05/P1000593-708x1024.jpg',
      'https://www.lisi-automotive.com/wp-content/themes/lisi/imgs/picto-previous.jpg',
      'https://www.lisi-automotive.com/wp-content/themes/lisi/imgs/picto-catalogue.png',
      'https://www.lisi-automotive.com/wp-content/themes/lisi/imgs/picto-contact.png',
      'https://www.lisi-automotive.com/wp-content/uploads/2017/06/picto-linkedin.jpg',
      'https://www.lisi-automotive.com/wp-content/uploads/2017/06/picto-facebook.jpg',
      'https://www.lisi-automotive.com/wp-content/uploads/2017/06/picto-youtube.png',
      'https://www.lisi-automotive.com/wp-content/uploads/2017/06/picto-viadeo.jpg',
      'https://www.lisi-automotive.com/wp-content/uploads/2017/06/picto-xing.jpg'
    ],
    "cssFiles": 30,
    "cssOrJsNotExt": 17,
    "filesWithError": [],
    "socialButtonsFound": [],
    "isStatic": false,
    "poweredBy": [ 'PHP/5.4.16', 'PleskLin' ],
    "protocolHTTP": 'https:',
    "cms": [ 'API CMS', 'wordpress' ],
    "loadTime": 1253,
    "ratioLazyLoad": 5.555555555555555,
    "ratioimagesResizedInPage": 33.33333333333333,
    "ratioHttp1": 0,
    "plugins": 0,
    "isMobileFriendly": false,
    "imageSrcEmpty": 0,
    "ratio_etags": 0.4834123222748815,
    "host": { "isGreen": true, "energy": 'groeneenergie' },
  },
}
